// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSSllgIx5Cyrax2YTR1dKv8LqSTt43kQo',
    appId: '1:834506709285:web:3bed3637cf657f897062cc',
    messagingSenderId: '834506709285',
    projectId: 'uap-app-f02f0',
    authDomain: 'uap-app-f02f0.firebaseapp.com',
    storageBucket: 'uap-app-f02f0.appspot.com',
    measurementId: 'G-3QXB5BP091',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERteD40rfs7EP-FsqIGRHkBs_SlfCPUo',
    appId: '1:834506709285:android:d8ffc4a8448e268b7062cc',
    messagingSenderId: '834506709285',
    projectId: 'uap-app-f02f0',
    storageBucket: 'uap-app-f02f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI5H_ZwB-Wd0ZQYfyHBk8CPHB-TLqfnHw',
    appId: '1:834506709285:ios:995ab3dac5900bce7062cc',
    messagingSenderId: '834506709285',
    projectId: 'uap-app-f02f0',
    storageBucket: 'uap-app-f02f0.appspot.com',
    iosBundleId: 'com.example.uapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI5H_ZwB-Wd0ZQYfyHBk8CPHB-TLqfnHw',
    appId: '1:834506709285:ios:105dedcc02685f447062cc',
    messagingSenderId: '834506709285',
    projectId: 'uap-app-f02f0',
    storageBucket: 'uap-app-f02f0.appspot.com',
    iosBundleId: 'com.example.uapApp.RunnerTests',
  );
}
